--
-- PostgreSQL database dump
--

\restrict IQdsWQtcluYuw9yTawBDOeQ9s49HTe5MpuEXowbO1oTH1MxLm798eUFI1u2hzAN

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: create_booking_request(text, text, text, text, date, time without time zone, bigint[]); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.create_booking_request(p_client_name text, p_phone text, p_email text, p_notes text, p_booking_date date, p_booking_time time without time zone, p_service_ids bigint[]) RETURNS bigint
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
declare
  new_booking_id bigint;
  calculated_duration integer;
  valid_service_count integer;
begin
  if trim(p_client_name) = '' then
    raise exception 'O nome da cliente é obrigatório.';
  end if;

  if trim(p_phone) = '' then
    raise exception 'O número de telemóvel é obrigatório.';
  end if;

  if p_service_ids is null or cardinality(p_service_ids) = 0 then
    raise exception 'É necessário escolher pelo menos um serviço.';
  end if;

  select
    count(*),
    coalesce(sum(duration), 0)
  into
    valid_service_count,
    calculated_duration
  from public.services
  where id = any(p_service_ids)
    and active = true;

  if valid_service_count <> cardinality(p_service_ids) then
    raise exception 'Um ou mais serviços não estão disponíveis.';
  end if;

  insert into public.bookings (
    client_name,
    phone,
    email,
    notes,
    booking_date,
    booking_time,
    total_duration,
    status
  )
  values (
    trim(p_client_name),
    trim(p_phone),
    nullif(trim(coalesce(p_email, '')), ''),
    nullif(trim(coalesce(p_notes, '')), ''),
    p_booking_date,
    p_booking_time,
    calculated_duration,
    'pending'
  )
  returning id into new_booking_id;

  insert into public.booking_services (
    booking_id,
    service_id,
    service_name,
    duration
  )
  select
    new_booking_id,
    id,
    name,
    duration
  from public.services
  where id = any(p_service_ids)
    and active = true;

  return new_booking_id;
end;
$$;


--
-- Name: is_admin(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.is_admin() RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'admin'
  );
$$;


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: blocked_dates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.blocked_dates (
    id bigint NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT blocked_dates_check CHECK ((end_date >= start_date))
);


--
-- Name: blocked_dates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.blocked_dates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blocked_dates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking_services; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking_services (
    id bigint NOT NULL,
    booking_id bigint NOT NULL,
    service_id bigint,
    service_name text NOT NULL,
    duration integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT booking_services_duration_check CHECK ((duration > 0))
);


--
-- Name: booking_services_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.booking_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookings (
    id bigint NOT NULL,
    client_name text NOT NULL,
    phone text NOT NULL,
    email text,
    notes text,
    booking_date date NOT NULL,
    booking_time time without time zone NOT NULL,
    total_duration integer NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT bookings_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'cancelled'::text, 'completed'::text]))),
    CONSTRAINT bookings_total_duration_check CHECK ((total_duration > 0))
);


--
-- Name: bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_settings (
    id integer DEFAULT 1 NOT NULL,
    has_lunch_break boolean DEFAULT false NOT NULL,
    lunch_start time without time zone,
    lunch_end time without time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT business_settings_id_check CHECK ((id = 1))
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profiles (
    id uuid NOT NULL,
    full_name text,
    role text DEFAULT 'admin'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: services; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.services (
    id bigint NOT NULL,
    category text NOT NULL,
    name text NOT NULL,
    duration integer NOT NULL,
    price numeric(10,2),
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT services_duration_check CHECK ((duration > 0))
);


--
-- Name: services_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: working_hours; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.working_hours (
    id bigint NOT NULL,
    weekday integer NOT NULL,
    is_open boolean DEFAULT true NOT NULL,
    start_time time without time zone,
    end_time time without time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT working_hours_weekday_check CHECK (((weekday >= 0) AND (weekday <= 6)))
);


--
-- Name: working_hours_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.working_hours ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.working_hours_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: blocked_dates; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.blocked_dates (id, start_date, end_date, reason, created_at) FROM stdin;
\.


--
-- Data for Name: booking_services; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.booking_services (id, booking_id, service_id, service_name, duration, created_at) FROM stdin;
4	2	23	Axilas	15	2026-08-03 19:51:48.132381+00
5	1	23	Axilas	15	2026-08-03 19:52:18.992959+00
7	4	23	Axilas	15	2026-08-03 22:24:53.081614+00
8	5	29	Limpeza de Pele	75	2026-08-04 14:58:07.346906+00
\.


--
-- Data for Name: bookings; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.bookings (id, client_name, phone, email, notes, booking_date, booking_time, total_duration, status, created_at, updated_at) FROM stdin;
2	Diogo Sousa	919798784	\N	\N	2026-08-04	18:00:00	15	accepted	2026-08-03 19:50:18.112003+00	2026-08-03 19:51:47.930694+00
1	Lara Lima Sousa	912461829	\N	\N	2026-08-04	18:15:00	15	accepted	2026-08-03 18:48:37.931391+00	2026-08-03 19:52:18.800475+00
4	Lara Sousa	912461829	\N	\N	2026-08-05	17:30:00	15	accepted	2026-08-03 22:24:53.081614+00	2026-08-03 22:34:26.013677+00
5	Martim	912461829	\N	\N	2026-08-07	09:30:00	75	rejected	2026-08-04 14:58:07.346906+00	2026-08-04 15:00:28.637249+00
\.


--
-- Data for Name: business_settings; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.business_settings (id, has_lunch_break, lunch_start, lunch_end, updated_at) FROM stdin;
1	f	\N	\N	2026-08-03 19:35:45.315518+00
\.


--
-- Data for Name: profiles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.profiles (id, full_name, role, created_at) FROM stdin;
01642f27-4ad5-4c27-b6cc-8715d29d5440	Mónica Lima	admin	2026-08-03 18:22:36.508203+00
fb16df4c-e481-4c6b-854c-412a792bd30e	Mónica Lima	admin	2026-08-03 22:29:12.167008+00
\.


--
-- Data for Name: services; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.services (id, category, name, duration, price, active, created_at) FROM stdin;
16	Unhas	Aplicação de Verniz Gel	60	\N	t	2026-08-03 18:28:37.782801+00
17	Unhas	Manutenção de Unhas de Gel	90	\N	t	2026-08-03 18:28:37.782801+00
18	Unhas	Aplicação de Extensões	120	\N	t	2026-08-03 18:28:37.782801+00
19	Unhas	Aplicação de Gelinho	60	\N	t	2026-08-03 18:28:37.782801+00
20	Unhas	Manicure Normal	45	\N	t	2026-08-03 18:28:37.782801+00
21	Pedicure	Pedicure Normal	60	\N	t	2026-08-03 18:28:37.782801+00
23	Depilação	Axilas	15	\N	t	2026-08-03 18:28:37.782801+00
24	Depilação	Sobrancelhas	15	\N	t	2026-08-03 18:28:37.782801+00
25	Depilação	Virilhas	20	\N	t	2026-08-03 18:28:37.782801+00
26	Depilação	Meia Perna	25	\N	t	2026-08-03 18:28:37.782801+00
27	Depilação	Perna Completa	40	\N	t	2026-08-03 18:28:37.782801+00
28	Depilação	Depilação Completa	90	\N	t	2026-08-03 18:28:37.782801+00
29	Estética	Limpeza de Pele	75	\N	t	2026-08-03 18:28:37.782801+00
30	Estética	Lifting de Pestanas	60	\N	t	2026-08-03 18:28:37.782801+00
22	Depilação	Buço	5	\N	t	2026-08-03 18:28:37.782801+00
\.


--
-- Data for Name: working_hours; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.working_hours (id, weekday, is_open, start_time, end_time, created_at) FROM stdin;
2	1	t	09:00:00	19:00:00	2026-08-03 18:20:39.06942+00
3	2	t	09:00:00	19:00:00	2026-08-03 18:20:39.06942+00
4	3	t	09:00:00	19:00:00	2026-08-03 18:20:39.06942+00
5	4	t	09:00:00	19:00:00	2026-08-03 18:20:39.06942+00
6	5	t	09:00:00	19:00:00	2026-08-03 18:20:39.06942+00
7	6	t	08:00:00	21:30:00	2026-08-03 18:20:39.06942+00
1	0	f	\N	\N	2026-08-03 18:20:39.06942+00
\.


--
-- Name: blocked_dates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.blocked_dates_id_seq', 1, true);


--
-- Name: booking_services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.booking_services_id_seq', 8, true);


--
-- Name: bookings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.bookings_id_seq', 5, true);


--
-- Name: services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.services_id_seq', 32, true);


--
-- Name: working_hours_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.working_hours_id_seq', 21, true);


--
-- Name: blocked_dates blocked_dates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blocked_dates
    ADD CONSTRAINT blocked_dates_pkey PRIMARY KEY (id);


--
-- Name: booking_services booking_services_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_services
    ADD CONSTRAINT booking_services_pkey PRIMARY KEY (id);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);


--
-- Name: business_settings business_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_settings
    ADD CONSTRAINT business_settings_pkey PRIMARY KEY (id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


--
-- Name: working_hours working_hours_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.working_hours
    ADD CONSTRAINT working_hours_pkey PRIMARY KEY (id);


--
-- Name: working_hours working_hours_weekday_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.working_hours
    ADD CONSTRAINT working_hours_weekday_key UNIQUE (weekday);


--
-- Name: bookings bookings_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER bookings_set_updated_at BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: business_settings settings_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER settings_set_updated_at BEFORE UPDATE ON public.business_settings FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: booking_services booking_services_booking_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_services
    ADD CONSTRAINT booking_services_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;


--
-- Name: booking_services booking_services_service_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_services
    ADD CONSTRAINT booking_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id) ON DELETE SET NULL;


--
-- Name: profiles profiles_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: blocked_dates Admins manage blocked dates; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins manage blocked dates" ON public.blocked_dates TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: booking_services Admins manage booking services; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins manage booking services" ON public.booking_services TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: bookings Admins manage bookings; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins manage bookings" ON public.bookings TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: business_settings Admins manage business settings; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins manage business settings" ON public.business_settings TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: services Admins manage services; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins manage services" ON public.services TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: working_hours Admins manage working hours; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins manage working hours" ON public.working_hours TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: profiles Admins read profiles; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins read profiles" ON public.profiles FOR SELECT TO authenticated USING (public.is_admin());


--
-- Name: profiles Admins update own profile; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins update own profile" ON public.profiles FOR UPDATE TO authenticated USING ((id = ( SELECT auth.uid() AS uid))) WITH CHECK ((id = ( SELECT auth.uid() AS uid)));


--
-- Name: booking_services Public can create booking services; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public can create booking services" ON public.booking_services FOR INSERT TO authenticated, anon WITH CHECK (true);


--
-- Name: bookings Public can create bookings; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public can create bookings" ON public.bookings FOR INSERT TO authenticated, anon WITH CHECK ((status = 'pending'::text));


--
-- Name: services Public can read active services; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public can read active services" ON public.services FOR SELECT TO authenticated, anon USING (((active = true) OR public.is_admin()));


--
-- Name: blocked_dates Public can read blocked dates; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public can read blocked dates" ON public.blocked_dates FOR SELECT TO authenticated, anon USING (true);


--
-- Name: business_settings Public can read business settings; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public can read business settings" ON public.business_settings FOR SELECT TO authenticated, anon USING (true);


--
-- Name: working_hours Public can read working hours; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public can read working hours" ON public.working_hours FOR SELECT TO authenticated, anon USING (true);


--
-- Name: blocked_dates; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.blocked_dates ENABLE ROW LEVEL SECURITY;

--
-- Name: booking_services; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.booking_services ENABLE ROW LEVEL SECURITY;

--
-- Name: bookings; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

--
-- Name: business_settings; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.business_settings ENABLE ROW LEVEL SECURITY;

--
-- Name: profiles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

--
-- Name: services; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

--
-- Name: working_hours; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.working_hours ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict IQdsWQtcluYuw9yTawBDOeQ9s49HTe5MpuEXowbO1oTH1MxLm798eUFI1u2hzAN

